version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.9
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres

  minio:
    container_name: minio_container
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    restart: always

  backend:
    container_name: backend
    image: safarajmanandhar/agrilink-backend
    build:
      context: .  # Adjust if your Dockerfile is in a different directory
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_PW=${DB_PW}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DB_CLIENT=${DB_CLIENT}
      - MINIO_HOST=minio
      - MINIO_PORT=9000
    ports:
      - "${PORT}:${PORT}"
    command: bash -c "npm start"
    restart: always
    depends_on:
      - postgres
      - minio
